name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-15

    steps:
    - uses: actions/checkout@v5

    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 16.4.0
        
    - name: Install Ruby
      run: bundle install
      
    - name: Mise install
      uses: jdx/mise-action@v2
      with:
        experimental: true

    - name: Install xrun
      run: |
         brew tap heroesofcode/taps
         brew install heroesofcode/taps/xrun

    - name: Run tests with xrun
      run: xrun project DeliveryApp.xcodeproj DeliveryApp 18.5 16

    - name: Danger action
      uses: MeilCli/danger-action@v6.0.34
      if: github.event_name == 'pull_request'
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5.4.3
      with:
        swift: true
        swift_project: DeliveryApp
        verbose: true
