name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3

    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 14.3
        
    - name: Install Ruby
      run: |
         eval "$(rbenv init -)"
         rbenv install -s `cat .ruby-version`
         bundle install

    - name: Build and Tests
      run: bundle exec fastlane tests
