name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3

    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 14.2
        
    - name: Set up Ruby 3.1.2
      uses: ruby/setup-ruby@v1.84.0
      with:
         ruby-version: 3.1.2
         bundler-cache: true

    - name: Build and Tests
      run: bundle exec fastlane tests
