name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3

    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 14.2
        
    - name: Install Ruby
      run: bundle install

    - name: Build and Tests
      run: bundle exec fastlane tests

    - name: Danger action
      uses: MeilCli/danger-action@v5.6.12
      if: github.event_name == 'pull_request'
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
