name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3

    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 14.2

    - name: Build and Tests
      run: set -o pipefail && xcodebuild test -scheme "DeliveryApp" -destination "platform=iOS Simulator,name=IPhone 8" clean test | xcpretty
