name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-14

    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 15.4
        
    - name: Install Ruby
      run: bundle install
      
    - name: Install Mint
      run: brew install mint
      shell: bash

    - name: Cache Mint packages
      uses: actions/cache@v4
      with:
        path: /usr/local/lib/mint/packages
        key: ${{ runner.os }}-mint-${{ hashFiles('**/metadata.json') }}
        restore-keys: ${{ runner.os }}-mint-
     
    - name: Install Mint Dependencies
      run: mint bootstrap
      shell: bash

    - name: Install xrun
      run: |
         brew tap heroesofcode/taps
         brew install heroesofcode/taps/xrun

    - name: Run tests with xrun
      run: xrun project DeliveryApp.xcodeproj DeliveryApp 17.5 15 fail

    - name: Danger action
      uses: MeilCli/danger-action@v6.0.15
      if: github.event_name == 'pull_request'
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.5.0
      with:
        swift: true
        swift_project: DeliveryApp
        verbose: true
